Repository udacity/deep-learning-v2-pytorch, pull requests merged in 2021-03, with the labels that each got.

#309 Good practice for next(iter(data))
  intro-to-pytorch/Part 3 - Training Neural Networks (Exercises).ipynb
Labels: enhancement

#304 fixed typo
  batch-norm/Batch_Normalization.ipynb
Labels: typo

#290 style : Correction in spelling
  recurrent-neural-networks/time-series/Simple_RNN.ipynb
Labels: typo

#260 Fix typos
  project-bikesharing/Predicting_bike_sharing_data.ipynb
Labels: typo

#228 Fixed typos in multiple jupyter notebooks
  dcgan-svhn/DCGAN_Exercise.ipynb
  dcgan-svhn/DCGAN_Solution.ipynb
  debug.log
  gan-mnist/MNIST_GAN_Exercise.ipynb
  gan-mnist/MNIST_GAN_Solution.ipynb
Labels: typo

#219 Small TODO fix
  attention/Attention_Basics.ipynb
Labels: bug

#212 Fix typo
  attention/Attention_Basics.ipynb
  attention/Attention_Basics_Solution.ipynb
Labels: typo

#301 Remove "_" from conv layer names to match figures.
  style-transfer/Style_Transfer_Exercise.ipynb
Labels: typo

#287 Fixing typo in Tensors in Pytorch (Exercises/Solutions)
  intro-to-pytorch/Part 1 - Tensors in PyTorch (Exercises).ipynb
  intro-to-pytorch/Part 1 - Tensors in PyTorch (Solution).ipynb
Labels: typo

#213 update miniconda installation guide links
  README.md
Labels: typo

#204 corrected minor typo
  project-bikesharing/Bike-Sharing-Dataset/Readme.txt
Labels: typo

#195 Updated the spelling !
  convolutional-neural-networks/conv-visualization/conv_visualization.ipynb
Labels: typo

#194 fixed minor typo (exercise notebook)
  cycle-gan/CycleGAN_Exercise.ipynb
Labels: typo

#226 Corrected CIFAR for GPU display
  convolutional-neural-networks/cifar-cnn/cifar10_cnn_augmentation.ipynb
  convolutional-neural-networks/cifar-cnn/cifar10_cnn_exercise.ipynb
  convolutional-neural-networks/cifar-cnn/cifar10_cnn_solution.ipynb
Labels: bug

#190 Fixed minor typo
  intro-to-pytorch/Part 7 - Loading Image Data (Solution).ipynb
Labels: typo

#189 Fixed minor typo
  intro-to-pytorch/Part 7 - Loading Image Data (Exercises).ipynb
Labels: typo

#184 Fixed typo
  intro-to-pytorch/Part 2 - Neural Networks in PyTorch (Solution).ipynb
Labels: typo

#180 fixed typo
  intro-to-pytorch/Part 2 - Neural Networks in PyTorch (Exercises).ipynb
Labels: typo

#179 fixed typo
  intro-to-pytorch/Part 2 - Neural Networks in PyTorch (Solution).ipynb
Labels: typo

#178 Fixed missing word in line
  intro-to-pytorch/Part 1 - Tensors in PyTorch (Exercises).ipynb
Labels: typo

#164 fix typo for comment
  recurrent-neural-networks/char-rnn/Character_Level_RNN_Exercise.ipynb
Labels: typo

#243 Fix ¨Visualize Sample Test Results¨ section (GPU)
  convolutional-neural-networks/cifar-cnn/cifar10_cnn_exercise.ipynb
Labels: bug

#286 Fixing filename in .udacity-pa for bikesharing project
  project-bikesharing/.udacity-pa/projects.py
Labels: bug

#269 torch.transpose() added in markdown
  .vscode/settings.json
  intro-to-pytorch/Part 1 - Tensors in PyTorch (Exercises).ipynb
  intro-to-pytorch/Part 2 - Neural Networks in PyTorch (Exercises).ipynb
  intro-to-pytorch/__pycache__/helper.cpython-37.pyc
Labels: enhancement

#253 added todo in Weight step
  project-bikesharing/my_answers.py
Labels: typo

#306 refactor: Generate images with no_grad() during Discriminator training
  gan-mnist/MNIST_GAN_Solution.ipynb
Labels: enhancement

#272 Fixing Key error in predict
  sentiment-rnn/Sentiment_RNN_Solution.ipynb
Labels: enhancement

#261 Fix for helpers.hist_dist() crash in weight_initialization notebook
  weight-initialization/helpers.py
Labels: enhancement

#170 Transposition .t() of vector added as one more option.
  intro-to-pytorch/Part 1 - Tensors in PyTorch (Exercises).ipynb
Labels: enhancement

#171 Precision set equal for numpy and torch, else tensor's values are rounded
  intro-to-pytorch/Part 1 - Tensors in PyTorch (Exercises).ipynb
Labels: enhancement

#239 Adapt output type of network.run to be printable
  project-bikesharing/Predicting_bike_sharing_data.ipynb
Labels: bug

#176 Add missing activation function
  intro-to-pytorch/Part 2 - Neural Networks in PyTorch (Solution).ipynb
Labels: typo

#173 Update Part 3 - Training Neural Networks (Exercises).ipynb
  intro-to-pytorch/Part 3 - Training Neural Networks (Exercises).ipynb
Labels: typo

#285 Update Part 8 - Transfer Learning (Exercises).ipynb
  intro-to-pytorch/Part 8 - Transfer Learning (Exercises).ipynb
Labels: bug

#106 Update dlnd_face_generation.ipynb
  project-face-generation/dlnd_face_generation.ipynb
Labels: enhancement

#198 Update Part 2 - Neural Networks in PyTorch (Solution).ipynb
  intro-to-pytorch/Part 2 - Neural Networks in PyTorch (Solution).ipynb
Labels: bug

#299 Update Sentiment_RNN_Solution
  sentiment-rnn/Sentiment_RNN_Solution.ipynb
Labels: bug

#197 fix: Clarify output dimension from cyclegan discriminators
  cycle-gan/CycleGAN_Exercise.ipynb
Labels: enhancement

#234 Rectifying error in comments
  gan-mnist/MNIST_GAN_Exercise.ipynb
Labels: typo

#224 [mnist_mlp_exercise] Remove Redundant np.sum() on a single cell
  convolutional-neural-networks/mnist-mlp/mnist_mlp_exercise.ipynb
Labels: enhancement

#167 [Image Style Transfer] Correct Gram Matrix function for Batch Size > 1
  style-transfer/Style_Transfer_Solution.ipynb
Labels: enhancement

#42 2.26 gradient descent
  intro-neural-networks/gradient-descent/GradientDescent.ipynb
Labels: bug
