Repository udacity/deep-learning-v2-pytorch, pull requests merged in 2021-06, with the labels that each got.

#327 Typo in line 324 "Postive" need to be "Positive"
  sentiment-analysis-network/Sentiment_Classification_Projects.ipynb
Labels: typo

#331 style: Fix the typo
  sentiment-analysis-network/Sentiment_Classification_Projects.ipynb
Labels: typo

#330 refactor: Change TODO self.layer_0 to None
  sentiment-analysis-network/Sentiment_Classification_Projects.ipynb
Labels: bug

#332 docs: add TODO in update_weights() function
  project-bikesharing/my_answers.py
Labels: feedback

#333 fix: Scale the targets for test data
  project-bikesharing/Predicting_bike_sharing_data.ipynb
Labels: bug
